### ISSUE TITLE
Add docs on how to use ld-r as dep

### ISSUE THREAD

**Issue by LaurensRietveld** [ali1k/ld-r#8]
The getting started wasn't what I expected it to be. Instead of cloning ld-r and building on top of that, I expected it to explain how to use ld-r as dependency in my own project

**Comment by ali1k** [comment]
will work on it soon...

**Comment by semanticfire** [comment]
I would like to know how to use LDR as a encapsulation method in my react app, right now LDR seems like a full stack, where I want to just inject properties insider generic react components

**Comment by ali1k** [comment]
Hi @semanticfire, as you mentioned LD-R is a full-stack framework. You can install it as a cloud service and employ the dynamic configurations to build your semantic web app. Most of the existing React components (except core Reactor components) can be easily re-used in other apps, however, you will lose the isomorphic nature and Flux data flow if you try to use them stand-alone.

**Comment by semanticfire** [comment]
That is what I guessed, is there no way to generate a 'Linked Data Redux' ??
That would be really helpfull

**Comment by ali1k** [comment]
Ii will think about it. However, I am not sure if Linked Data Redux would differ a lot from the normal Redux. What LD-R does now is just adopting Fluxible data flow (not Redux) for Linked Data. The magic is more on the RDF components + server-side services communicating with SPARQL endpoints.

**Comment by darrencruse** [comment]
Just a note that I too would be interested in a way to use ld-r react components in an existing app.

In my case there's an existing app built with node/webpack/react/redux (so not all that different except redux instead of fluxible).

The app currently stores it's data as json documents in dynamodb but I was looking to convert the plain json to json-ld and use virtuoso to house the rdf generated from the json-ld.

So in my case there is a lot of existing code including parts doing authentication and stuff that won't/can't change.  And even UI and styling and stuff that I would be hoping wouldn't have to change since the users have gotten used to certain things.

Yet I do have *some* flexibility, and from doing the tutorial I do see value in ld-r if I were able to incorporate it into the existing app instead of starting from square one and rebuilding the app on ld-r from the ground up.

I was imagining a world where in the future I might use the provided ld-r components to more quickly develop new features or for certain "admin" type UI, and possibly write custom components to configure for certain properties where I need to (like the tutorial said).

But with my app being the foundation not the ld-r app.

Sounds like it's not easy but just fwiw it would be awesome if it were possible...

(if it's not impossible just hard - I might snoop in the code and see if there's any chance I could contribute changes to help it happen?)

**Comment by ali1k** [comment]
dear @darrencruse @semanticfire 
When I find some spare time, I will investigate this possibility and then might come back to you for some help in realising this nice feature.
What comes from top of my mind is that: React components in LD-R should be bundled with their actions, stores and services to support the flux data flow. We need a solution that bundles Flux into a reusable and interoperable stand-alone app...
